<?php
Route::get('/', function () {return view('auth.login');});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/sendmail', 'HomeController@sendmail');
Route::post('/home/newpassword', 'HomeController@newpassword');
Route::get('/dashboard', 'DashboardController@index');
Route::resource('suppliers','SuppliersController');
Route::resource('portaluser','PortaluserController');
Route::resource('statistics','StatisticsController');
Route::resource('clients','ClientsController');
Route::resource('campaign','CampaignController');
Route::get('campaign/{site}/delete', ['as' => 'campaign.delete', 'uses' => 'CampaignController@destroy']);
Route::post('campaign/getCampaignsByClient/','CampaignController@getCampaignsByClient');
Route::resource('donotcalls','DonotcallsController');
Route::resource('salaciouswords','SalaciouswordsController');
Route::resource('emailblacklists','EmailblacklistsController');
Route::resource('domainblacklists','DomainblacklistsController');
Route::resource('nameblacklists','NameblacklistsController');
Route::get('quarantines/delete/{id}', 'QuarantinesController@delete');
Route::resource('quarantines','QuarantinesController');
Route::get('donotcalls-export-csv/{type}', array('as'=>'excel-file','uses'=>'DonotcallsController@downloadExcelFile'));
Route::get('salaciouswords-export-csv/{type}', array('as'=>'excel-file','uses'=>'SalaciouswordsController@downloadExcelFile'));
Route::get('domainblacklists-export-csv/{type}', array('as'=>'excel-file','uses'=>'DomainblacklistsController@downloadExcelFile'));
Route::get('emailblacklists-export-csv/{type}', array('as'=>'excel-file','uses'=>'EmailblacklistsController@downloadExcelFile'));
Route::get('nameblacklistsController-export-csv/{type}', array('as'=>'excel-file','uses'=>'NameblacklistsController@downloadExcelFile'));
Route::get('/quarantines/download/{quarantines}', 'QuarantinesController@downloadExcelFile');
Route::resource('alerts', 'AlertsController');
Route::post('/alerts/ackalert', 'AlertsController@acknowledgeAlert');
Route::get('/alerts/download/{file}', 'AlertsController@getDownload');
Route::post('/alerts/getAlertsCount', 'AlertsController@getAlertsCount');
Route::post('/home/username', 'HomeController@getUsername');
Route::post('/home/password', 'HomeController@getPassword');
Route::post('/clients/upload', 'ClientsController@upload');
Route::post('processleadcsv/processcsv','ProcessleadcsvController@processcsv');
Route::resource('processleadcsv','ProcessleadcsvController');
Route::group(['prefix' => 'api/v1'], function(){
	Route::resource('leadprocessing', 'Api\LeadProcessingController');
});